function [x,F] = mapping_opt(Phi, refL, refR, IntrinsicMatrix, RotationMatrix, TranslationMatrix,plane, V, centroid, xgrid, ygrid, xyrange, d, maxit)

options = optimoptions('fminunc','Algorithm','quasi-newton', 'display', 'iter',...
     'MaxIterations', maxit, 'UseParallel', true);  
  
[x,F] = fminunc(@(Phi)mapping_obj(Phi, refL, refR, ...
                                  IntrinsicMatrix, RotationMatrix, TranslationMatrix,  ...
                                  plane, V, centroid, xgrid, ygrid, xyrange, d), ...
                                  Phi(:), options);
end

